name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New Code Example
        - New Documentation
        - Repository Enhancement
        - CI/CD Improvement
        - Other
    validations:
      required: true

  - type: dropdown
    id: language
    attributes:
      label: Programming Language
      description: Which language does this feature relate to?
      options:
        - C++
        - Java
        - Both
        - Not Applicable
    validations:
      required: true

  - type: input
    id: topic
    attributes:
      label: Related Topic/Lecture
      description: Which topic or lecture is this related to?
      placeholder: "e.g., Lecture 05: Function Overloading"
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "A clear description of what the problem is. Ex. I'm always frustrated when [...]"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: Any alternative solutions or features you've considered
    validations:
      required: false

  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: How would this feature help students learning OOP?
      placeholder: |
        - Better understanding of concepts
        - More practical examples
        - Improved documentation
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Very important
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request
      placeholder: Any additional information
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute this feature?
      options:
        - label: I'm willing to submit a pull request for this feature
          required: false
